build:
  version: "3.0.0"

accounts:
  message: "Welcome to Duncan Cadoret Bank accounts related APIs [dev side]"
  contactDetails:
    name: "Duncan Cadoret"
    role: "Software Engineer One day"
    website: "https://duncan-cadoret.com/"
  onCallSupport:
    - (33) 6 12 34 56 78
    - (33) 6 12 34 56 79