build:
  version: "1.0.0"

cards:
  message: "Welcome to Duncan Cadoret Bank CARDS related to Production APIs [Production side]"
  contactDetails:
    name: "Samuel Production"
    role: "Product Owner"
    website: "https://facebook.com/"
  onCallSupport:
    - (33) 6 12 34 56 80
    - (33) 6 12 34 56 81