build:
  version: "2 .0.0"

loans:
  message: "Welcome to Duncan Cadoret Bank LOANS related to QA APIs [QA side]"
  contactDetails:
    name: "Madame de la QA"
    role: "QA Leader"
    website: "https://google.com/"
  onCallSupport:
    - (666) 30 11 22 33