spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/DuncanC42/D-Bank_configserver.git"
          search-paths: "src/main/resources/config" #ne mettre qui si les fichiers ne sont pas à la racine du repo
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true
