spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/DuncanC42/D-Bank_configserver.git"
          search-paths: "src/main/resources/config" #ne mettre qui si les fichiers ne sont pas à la racine du repo
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071
